//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Datos.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RECEPCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_RECEPCION()
        {
            this.TBL_STOCK = new HashSet<TBL_STOCK>();
        }
    
        public int rcp_id { get; set; }
        public int usu_id { get; set; }
        public System.DateTime rcp_fecha { get; set; }
    
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOCK> TBL_STOCK { get; set; }
    }
}
