//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Datos.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PRODUCTO()
        {
            this.TBL_STOCK = new HashSet<TBL_STOCK>();
            this.NUB_CARRO_PRODUCTOS = new HashSet<NUB_CARRO_PRODUCTOS>();
        }
    
        public int pro_id { get; set; }
        public string pro_nombre { get; set; }
        public string pro_detalle { get; set; }
        public int pro_precio { get; set; }
        public int pro_stock { get; set; }
        public Nullable<int> pro_critico { get; set; }
        public string pro_precio_oferta { get; set; }
        public Nullable<int> tprod_id { get; set; }
        public int pro_disponibilidad { get; set; }
        public string pro_imagen { get; set; }
    
        public virtual TBL_TIPO_PRODUCTO TBL_TIPO_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOCK> TBL_STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NUB_CARRO_PRODUCTOS> NUB_CARRO_PRODUCTOS { get; set; }
    }
}
