//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Datos.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LISTA_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_LISTA_COMPRA()
        {
            this.TBL_COMPRA = new HashSet<TBL_COMPRA>();
            this.NUB_LISTA_PRODUCTOS = new HashSet<NUB_LISTA_PRODUCTOS>();
        }
    
        public int lcom_id { get; set; }
        public int lcom_valor { get; set; }
        public int usu_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_COMPRA> TBL_COMPRA { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NUB_LISTA_PRODUCTOS> NUB_LISTA_PRODUCTOS { get; set; }
    }
}
