//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Datos.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STOCK
    {
        public int stk_id { get; set; }
        public int pro_id { get; set; }
        public int tstk_id { get; set; }
        public int rcp_id { get; set; }
        public int ordn_id { get; set; }
    
        public virtual TBL_ORDEN_STOCK TBL_ORDEN_STOCK { get; set; }
        public virtual TBL_RECEPCION TBL_RECEPCION { get; set; }
        public virtual TBL_TIPO_STOCK TBL_TIPO_STOCK { get; set; }
        public virtual TBL_PRODUCTO TBL_PRODUCTO { get; set; }
    }
}
